# Generated by Django 2.1.5 on 2019-02-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
