# Generated by Django 2.1.5 on 2019-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20190210_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
